### ISSUE TITLE
Fails if wallet address has interacted with unsupported pool contracts

### ISSUE THREAD

**Issue by cryptonomous** [rupebac/rsk_taxes#1]
Encountered this while trying to run myself. I had toyed around with depositing some money into the rBTC/FISH pool a few months ago, and rsk_taxes crashes when it encounters those transactions.

I tried to fix it by adding the following line to ContractSpecs.java:
```BTC_FISH_POOL("0x35a74a38fd7728f1c6bc39ae3b18c974b7979ddd", "BTC", "FISH");```

This allows the program to run without crashing, but it still doesn't seem to pick up the "add liquidity" events for the rBTC/FISH pool, only the "remove liquidity" events.

**Comment by rupebac** [comment]
Could you please give me your public wallet address so that I can debug it?

Thanks!
Ruben

**Comment by cryptonomous** [comment]
0x4bA233eD75f8f5FB29A73305B44B928456ABba14

**Comment by cryptonomous** [comment]
Just FYI in case it helps, my debugging efforts led me to StepsFilter's ```isAddLiquidity``` function. At that point, is the transaction data being properly decoded for the FISH pool transactions?

**Comment by rupebac** [comment]
Yes, I think I found your add liquidity transaction. It is this one right?

https://explorer.rsk.co/tx/0xc975b79ef2cc6d7e82bedc8a4cec333baa38bdf559580987ea28ee16806e7567

But this looks very very strange. That contains only one approval step...
like if it is incomplete... I don't see any

If you go to Sovryn, and go liquidity pool history... can you find the add
liquidity transaction there? and confirm that the transaction hash is the
same one as what I have put up here.

Regards,
Ruben

**Comment by cryptonomous** [comment]
Perhaps that is a failed transaction? I know I've had to reattempt transactions in Sovryn at least a few times.

According to my history this is the correct hash for my "Add to rBTC/FISH Pool" transaction:
https://explorer.rsk.co/tx/0xba207f38567d824f3e0c31ee792b0f63f2f02dad5a1785223f17691b398aa485

**Comment by rupebac** [comment]
I have found the problem! :)

covalenthq returns only the first 100 transactions in the first request,
you have to keep iterating the multiple pages... Will fix it and let you
know :)

Ruben

**Comment by cryptonomous** [comment]
Makes sense to me! I was beginning to suspect something of that nature as I just noticed some other missing transactions, but didn't notice anything particularly constraining in the API call itself.

I sent you a friend request on Discord (similarly themed username) - happy to chat there about collaborating on this project!
